Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BabyStore.Models;
using BabyStore.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BabyStore.Controllers
{ 
    public class BasketController : Controller
    {
        private readonly BabyStoreContext _context;
        public BasketController(BabyStoreContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            Basket basket = Basket.GetBasket(_context);
            BasketViewModel viewModel = new BasketViewModel
            {
                BasketLines = basket.GetBasketLines(),
                TotalCost = basket.GetTotalCost()
            };
            foreach (var item in basket.GetBasketLines())
            {
                ViewData[item.Product.Name] = _context.ProductImageMapping.Include(p => p.ProductImage).Where(p=>p.ProductID==item.ProductId).ToList();
            }
            
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToBasket(int id, int quantity)
        {
            Basket b = new Basket(_context);
            Basket basket = Basket.GetBasket(_context);
            basket.AddToBasket(id, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBasket(BasketViewModel viewModel)
        {
            Basket basket = Basket.GetBasket(_context);
            basket.UpdateBasket(viewModel.BasketLines);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult RemoveLine(int id)
        {
            Basket basket = Basket.GetBasket(_context);
            basket.RemoveLine(id);
            return RedirectToAction("Index");
        }

        public PartialViewResult Summary()
        {
            Basket basket = Basket.GetBasket(_context);
            BasketSummaryViewModel viewModel = new BasketSummaryViewModel
            {
                NumberOfItems = basket.GetNumberOfItems(),
                TotalCost = basket.GetTotalCost()
            };
            Debug.WriteLine(basket.GetTotalCost() + "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrrrr");
            return PartialView(viewModel);
        }
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BabyStore.Models;
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;

namespace BabyStore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly BabyStoreContext _context;

        public CategoriesController(BabyStoreContext context)
        {
            _context = context;
        }

        // GET: Categories
        [AllowAnonymous]                                   //So that anyone can view the list of categories without logging in
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.OrderBy(c=>c.Name).ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.ID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,byte[] rowVersion)
        {
            string[] fieldsToBind = new string[] { "Name", "RowVersion" };
            if (id == null)
            {
                return NotFound();
            }
            var categoryToUpdate = await _context.Category.FindAsync(id);
            if(categoryToUpdate==null)
            {
                Category deletedCategory = new Category();
                await TryUpdateModelAsync(deletedCategory,"",s=>s.ID,s=>s.Name,s=>s.RowVersion);
                ModelState.AddModelError(string.Empty, "Unable to save your changes because the " +
                    "category has been deleted by another user.");
                return View(deletedCategory);
            }
            if (await TryUpdateModelAsync(categoryToUpdate,"",s=>s.ID,s=>s.Name,s=>s.RowVersion))
            {
                try
                {
                    _context.Entry(categoryToUpdate).OriginalValues["RowVersion"] = rowVersion;
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exEntry = ex.Entries.Single();
                    var currentUIValues = (Category)exEntry.Entity;
                    var databaseCategory = exEntry.GetDatabaseValues();
                    if (databaseCategory == null)
                    {
                        ModelState.AddModelError(string.Empty, "Unable to save your changes because " +
                            "the category has been deleted by another user.");
                    }
                    else
                    {
                        var databaseCategoryValues = (Category)databaseCategory.ToObject();
                        if (databaseCategoryValues.Name != currentUIValues.Name)
                        {
                            ModelState.AddModelError("Name", "Current value in database: " + databaseCategoryValues.Name);
                        }
                        ModelState.AddModelError(string.Empty, "The record has been modified by  " +
                            "another user after you loaded the screen. Your changes have not yet been saved. " + 
                            "The new values in the database are shown below. If you want to overwrite these values" +
                            " with your changes then click save otherwise go back to the categories page.");
                        categoryToUpdate.RowVersion = (byte[])databaseCategoryValues.RowVersion;
                        ModelState.Remove("RowVersion");   //This is must because ModelState has the old RowVersion value. In the Razor Page the ModelState value for a field takes precedence over the model property values when bot are present
                    }
                }
            }
            return View(categoryToUpdate);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id,bool? deletionError)
        {
            if (id == null)
            {
                return NotFound();
            }

            string query = "Select * from Category where ID=@p0";
            var category = await _context.Category.FromSql(query, id).SingleOrDefaultAsync();
                
            if (category == null)
            {
                if (deletionError.GetValueOrDefault())
                {
                    return RedirectToAction("Index");
                }
                return NotFound();
            }
            if(deletionError.GetValueOrDefault())
            {
                ModelState.AddModelError(string.Empty, "The category you attempted to delete has been " +
                    "modified by another user after you loaded it. " + "The delete has not been" +
                    " performed. The current values in the database are shown above. " + "If you still " +
                    "want to delete this record click the Delete button again, otherwise go back to the categories page.");
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Category category)
        {
            
            try
            {
                _context.Entry(category).State = EntityState.Deleted;
                    var products = await _context.Product
                 .Where(d => d.CategoryID == category.ID)
                .ToListAsync();
                products.ForEach(d => d.CategoryID = null);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Delete", new { deletionError = true, id = category.ID });
            }
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using BabyStore.Data   
@using Microsoft.AspNetCore.Mvc.Rendering;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BabyStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-static-top border-bottom box-shadow mb-5">

            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BabyStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Shop by Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-route="ProductsIndex">View all our Products</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                    }
                </ul>
                @using (Html.BeginRouteForm("ProductsIndex", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                {
                    <div class="form-inline">
                        @Html.TextBox("Search", null, new
                   {
                       @class = "form-control mr-sm-2",
                       @placeholder
                                 = "Search Products"
                   })
                            
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                }

            </div>
            @Html.Action("Summary","Basket",new { area = "" })
            <partial name="_LoginPartial" />
            
        </nav>

    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div>
            &copy; 2019 - BabyStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_ProductEditCreatePartial.cshtml
@model BabyStore.ViewModel.ProductViewModel

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>      <!--The <span> tag provides a way to add a hook to a part of a text or a part of a document-->
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label"></label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Price" class="control-label"></label>
    <input asp-for="Price" class="form-control" />
    <span asp-validation-for="Price" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="CategoryID" class="control-label"></label>
    @Html.DropDownListFor(vm => vm.CategoryID, Model.CategoryList, htmlAttributes: new { @class = "form-control" })
    @*<select asp-for="CategoryID" class="form-control" asp-items="Model.CategoryList"></select>*@
    <span asp-validation-for="CategoryID" class="text-danger"></span>
</div>
@for (int i = 0; i < Model.ImageLists.Count; i++)
{
    <div class="form-group">
        <label class="control-label">Product Image @(i + 1):</label>
        @Html.DropDownListFor(vm => vm.ProductImages, Model.ImageLists[i], "Choose Image", htmlAttributes: new { @class = "form-control" })
        @*<select asp-for="ImageLists" class="form-control" asp-items="Model.ImageLists[i]" > </select>*@
        <span asp-validation-for="ImageLists" class="text-danger"></span>
    </div>
}